### ISSUE TITLE
where filter with regexp doesn't work

### ISSUE THREAD

**Issue by JyotiRani** [strongloop/loopback-connector-dashdb#51]
I am facing some issue with regexp filter. I am using dash db and have many records with taskCode field like TSK001, TSK002, BFTSK001 etc. but when i use the following url to query based on regexp it returns no result.

https://tasksrestnew.mybluemix.net/api/tasks?filter[where][taskCode][regexp]=/^B

https://tasksrestnew.mybluemix.net/api/tasks?filter[where][taskCode][regexp]=/^TSK

Additional information:
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-connector-dashdb": "^1.0.18",

Looks like regexp is not honored. Please validate and confirm.

**Comment by jannyHou** [comment]
Thanks we will take a look and make a plan for it.

**Comment by virkt25** [comment]
This will be a new feature as it is not currently supported by the dashDB connector. 

#Acceptance
- [ ] Implement Regexp filter for dashDB Connector.
- [ ] Test all filter scenarios not just where. 
- [ ] Update documentation for connector.

**Comment by ssh24** [comment]
This issue should be fixed on the next release of the dashdb connector.
