### ISSUE TITLE
Define custom type for property

### ISSUE THREAD

**Issue by FMGordillo** [strongloop/loopback-connector-dashdb#70]
# Description/Steps to reproduce

Using "type" as "number" it doesn't match my needs, and I need a longer value. I wanted to use BIGINT, so for that case:
```
...
"phone_number": {
      "type": "bigint",
      "required": true
    }
...
```

But this doesn't work

**Comment by FMGordillo** [comment]
Bump

**Comment by qpresley** [comment]
@FMGordillo Is this an issue when creating tables through the connector?  If so, then we may have to make a change to allow you to specify types other than the standard JavaScript types.  Today the connector sees `Number` as a DashDB type of `INTEGER` which is valid for many users however there is no way currently to specify a type for `BIGINT`.

**Comment by qpresley** [comment]
@FMGordillo there is a method of doing this in a current model definition.  Here is the test example that creates a BIGINT column
```
NumberData = db.define('NumberData', {
      number: {type: Number, null: false, index: true, unsigned: true,
        dataType: 'DECIMAL', precision: 10, scale: 3},
      tinyInt: {type: Number, dataType: 'SMALLINT', display: 2},
      mediumInt: {type: Number, dataType: 'INTEGER', unsigned: true,
        required: true},
      floater: {type: Number, dataType: 'DECIMAL', precision: 16, scale: 7},
      bigInt: {type: Number, dataType: 'BIGINT', unsigned: true,
        required: true},
    });
```

Node.js until VERY recently  did not have a Number greater that 53 bits while the DB2 BIGINT is a 63 bit value.  The example above will allow you to put the largest Node.js Number into a BIGINT column in a DB2 table.

**Comment by FMGordillo** [comment]
Thank you SO much!!!
