### ISSUE TITLE
Improvement : Infer some environment variables to make 'local' npm test easier

### ISSUE THREAD

**Issue by emonddr** [strongloop/loopback-connector-dashdb#83]
Related to https://github.com/strongloop/loopback-connector-dashdb/pull/82 : 

See comments:  [one](https://github.com/strongloop/loopback-connector-dashdb/pull/82#discussion_r304955348) and [two](https://github.com/strongloop/loopback-connector-dashdb/pull/82#discussion_r304996907)

When running `npm test` locally, user has to set certain environment variables .

If provided/computed schema name does not follow a certain pattern, then cleanup of that schema never happens and specific test(s) can fail.

User has to properly set DASHDB_SCHEMA, or get the schema name computed by
instead setting these:

export PACKAGE_NAME=loopback-connector-dashdb 
export BUILD_NUMBER={build number}   For example: 1
export nodeVersion={node version}    For example: 10

@bajtos suggests we improve the test suite so that we **don't** need these
variables to be set:
```
DASHDB_SCHEMA
PACKAGE_NAME
BUILD_NUMBER
nodeVersion
```

**Comment by emonddr** [comment]
The Jenkins job runs this test suite without problems.

Running locally, the test suite can fail if environment variables aren't properly set.

Let's make it easier for folks to run this locally.

:)

P.S. We may need to look at all relation database connectors and see if they require the same re-work as well.

**Comment by dhmlau** [comment]
@emonddr, this task is at a lower priority, so I'm removing the `needs estimate` label for now. Thanks.
