### ISSUE TITLE
Cannot read property 'affectedRows' of undefined

### ISSUE THREAD

**Issue by rbetjes** [strongloop/loopback-connector-dashdb#89]
I'm running into above error crashing the loopback instance with an exit status 1.
It happens when a PATCH request is updating a row and the db2 database returns an error.
I have found the reason and can produce a PR to fix it.

# Description/Steps to reproduce

Do a PATCH request on an entity which receives an error from the database.
In our case update a column that has the DOUBLE datatype with a value that has a wrong scale value.

# Expected result

We expect an error result with status 500. 
But actually the application exits without returning anything.

# Additional information

darwin x64 9.11.2
loopback-connector@4.9.0
loopback-ibmdb@2.5.1

**Comment by dhmlau** [comment]
@rbetjes, if you found the reason and can create a PR, please do so! Thanks!

**Comment by rbetjes** [comment]
Here you go: #91

**Comment by dhmlau** [comment]
PR #91 has landed. Closing as done.
Thanks again, @rbetjes! 👏
